version: "3"
services:
  nginx:
    image: nginx:latest
    env_file: .env
    ports:
      - 80:80
    volumes:
      - "./devops-home/:/var/www/devops-home/"
      - "./config/nginx/conf.d/devops.conf:/etc/nginx/conf.d/default.conf"
    restart: always 
    depends_on:
      - gitlab
      - jenkins
  gitlab:
    image: gitlab/gitlab-ce
    hostname: gitlab.devops.com
    env_file: .env
    environment: 
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://ctsc01232364201.cts.com/gitlab'
    ports:
      - "1443:443"
      - "122:22"
      - "8080:80"
    volumes:
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    restart: always
  jenkins:
    image: jenkins/jenkins 
    hostname: jenkins.devops.com
    env_file: .env
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    ports:
      - 8180:8080
      - 50000:50000
    volumes:
      - "/srv/jenkins:/var/jenkins_home"
      - "./config/jenkins/settings.xml:/var/jenkins_home/.m2/settings.xml"
      #- "./config/jenkins/config.xml:/usr/share/jenkins/ref/config.xml.override"
    restart: always
  nexus:
    image: sonatype/nexus3
    hostname: nexus.devops.com
    env_file: .env
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    environment:
      - NEXUS_CONTEXT=nexus
    volumes:
      - "/srv/nexus/nexus-data/:/nexus-data/"
    restart: always
  cadvisor:
    image: google/cadvisor:latest
    hostname: cadvisor.devops.com
    env_file: .env
    ports:
      - 8181:8080
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    depends_on:
      - nexus
    restart: always
  sonarqube:
    image: sonarqube
    hostname: sonarqube.devops.com
    ports:
      - 9000:9000
      - 9092:9092 
    env_file: .env
    command: -Dsonar.web.context=/sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - /srv/sonarqube/data:/opt/sonarqube/data
      - /srv/sonarqube/extensions:/opt/sonarqube/extensions
    restart: always
    depends_on:
      - nexus
      - postgres
  postgres:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /srv/postgresql:/var/lib/postgresql
      - /srv/postgresql/data:/var/lib/postgresql/data
    restart: always
